spring:
  application:
    name: Exambyte

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: read:public_repo

server:
  error:
    whitelabel:
      enabled: false

roles:
  correctors:
    - 11
    - 12
  organizers:
    - 106469655
    - 12
